name: 'Bump Nuget Version'
description: 'This action will add a Nuget source'
inputs:
  level:
    description: 'Version level (patch, minor or major)'     
    required: false
    default: ${{ contains(github.event.head_commit.message, '[PATCH]') && 'patch' || contains(github.event.head_commit.message, '[MINOR]') && 'minor' || contains(github.event.head_commit.message, '[MAJOR]') && 'major' || 'prerelease' }}
  csproj:
    description: 'CsProj full path'
    required: true
    
runs:
  using: 'composite'
  steps: 
    - run: sudo npm install -g semver
      shell: bash
    - run: export level=${{ inputs.level }}; export csproj=${{ inputs.csproj }}; ${{ github.action_path }}/bump.sh
      shell: bash
