name: Clean PR Cache
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:    
    uses: unosquare/bump-npm-version/.github/workflows/clean-pr-cache.yml@master
    with:
      repo-name: ${{ github.repository }}
      branch: ${{ github.ref_name }}
    secrets:
      github-token: ${{ secrets.GPR_ACCESS_TOKEN }}
